name: Twilio Spring Boot CI

on:
  push:
    branches:
      - master
  pull_request:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java: [8, 11.0.x]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Display Java version
        run: java -version

      - name: Check project
        run: ./gradlew check

      - name: Build and test
        run: ./gradlew build test
  publish:
    runs-on: ubuntu-18.04
    needs: build
    name: Publication
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x

      # Workaround until GitHub provides functionality to manually trigger actions
      # https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/m-p/33361/highlight/true#M1475
      - name: Release publication
        if: github.event_name == 'repository_dispatch'
        run: ./gradlew build -x test $RELEASE_TYPE -Prelease.scope=$RELEASE_SCOPE publish
        env:
          RELEASE_SCOPE: ${{ github.event.client_payload.release_scope }}
          RELEASE_TYPE: ${{ github.event.client_payload.release_type }}
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
